# Generated by Django 4.1.5 on 2023-01-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangobackend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="barcode",
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
