# Generated by Django 4.1.5 on 2023-01-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangobackend", "0002_remove_product_barcode_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="selected_images",
            field=models.CharField(default=1000, max_length=500),
            preserve_default=False,
        ),
    ]
