# Generated by Django 4.1.5 on 2023-01-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangobackend", "0005_subtituteproduct_rename_products_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="subtituteProduct",
            new_name="SubstituteProduct",
        ),
    ]
